name: Build Windows EXE

on:
  workflow_dispatch:
  push:


jobs:

  build:

    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"


    - name: Download FFmpeg
      shell: pwsh
      run: |

        Invoke-WebRequest `
          -Uri "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z" `
          -OutFile "ffmpeg.7z"

        7z x ffmpeg.7z

        $folder = Get-ChildItem -Directory -Filter "ffmpeg-*" | Select-Object -First 1

        Copy-Item "$($folder.FullName)\bin\ffmpeg.exe" "ffmpeg.exe"



    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt


    - name: Build EXE
      run: |
        pyinstaller build.spec


    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: AutoPlateBlur_V1
        path: dist/
