name: Build Windows EXE

on:
  workflow_dispatch:
  push:

jobs:

  build:

    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"


    - name: Download FFmpeg
      run: |
        curl -L https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip -o ffmpeg.zip
        tar -xf ffmpeg.zip
        mkdir ffmpeg
        copy ffmpeg-*/bin/ffmpeg.exe ffmpeg/ffmpeg.exe


    - name: Install Python packages
      run: |
        pip install -r requirements.txt


    - name: Build EXE
      run: |
        pyinstaller build.spec


    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: AutoPlateBlur_V1
        path: dist/
